# Generated by Django 4.2.1 on 2023-12-16 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="subjectData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjectName", models.CharField(max_length=50)),
                ("batchCode", models.CharField(max_length=20)),
                ("subjectCode", models.CharField(max_length=20)),
                (
                    "username",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subjectStudentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentId", models.CharField(max_length=30)),
                (
                    "subjectCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Manegar.subjectdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="attendanceDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendanceDate", models.DateField()),
                (
                    "subjectCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Manegar.subjectdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentId", models.CharField(max_length=30)),
                ("attendance", models.BooleanField(default=False)),
                (
                    "attendanceDate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Manegar.attendancedate",
                    ),
                ),
            ],
        ),
    ]
