# Generated by Django 4.2.4 on 2023-12-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0002_alter_subjectdata_subjectcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="additional",
            field=models.IntegerField(default=0),
        ),
    ]
