# Generated by Django 4.2.4 on 2023-12-09 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0003_remove_subjectdata_teacherid_subjectdata_teacher_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectstudentdata",
            old_name="subjectCode",
            new_name="batchCode",
        ),
    ]
