# Generated by Django 4.2.4 on 2023-12-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0003_attendance_additional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="additional",
        ),
        migrations.AddField(
            model_name="attendancedate",
            name="additional",
            field=models.IntegerField(default=0),
        ),
    ]
