# Generated by Django 4.2.4 on 2023-12-09 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0004_rename_subjectcode_subjectstudentdata_batchcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectdata",
            old_name="teacher_id",
            new_name="username",
        ),
    ]
