# Generated by Django 4.2.4 on 2023-12-10 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0006_rename_username_subjectdata_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectdata",
            name="subjectCode",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="batchCode",
            field=models.CharField(max_length=20),
        ),
    ]
