# Generated by Django 4.2.4 on 2023-12-10 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0007_subjectdata_subjectcode_alter_subjectdata_batchcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectstudentdata",
            old_name="batchCode",
            new_name="subjectCode",
        ),
    ]
