# Generated by Django 4.2.4 on 2023-12-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0008_rename_batchcode_subjectstudentdata_subjectcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectstudentdata",
            name="attendanceDate",
        ),
        migrations.CreateModel(
            name="attendanceDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendanceDate", models.DateField()),
                (
                    "subjectCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Manegar.subjectdata",
                    ),
                ),
            ],
        ),
    ]
