# Generated by Django 4.2.4 on 2023-12-11 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0009_remove_subjectstudentdata_attendancedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedate",
            name="studentId",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
