# Generated by Django 4.2.4 on 2023-12-11 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0010_attendancedate_studentid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectdata",
            old_name="user",
            new_name="teacher_id",
        ),
    ]
