# Generated by Django 4.2.1 on 2023-12-12 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0011_rename_user_subjectdata_teacher_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectdata",
            old_name="teacher_id",
            new_name="username",
        ),
    ]
