# Generated by Django 4.2.1 on 2023-12-13 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0012_rename_teacher_id_subjectdata_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancedate",
            name="studentId",
        ),
    ]
