# Generated by Django 4.2.1 on 2023-12-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Manegar", "0013_remove_attendancedate_studentid"),
    ]

    operations = [
        migrations.CreateModel(
            name="attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentId", models.CharField(max_length=30)),
                ("attendance", models.BooleanField(default=False)),
                (
                    "attendanceDate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Manegar.attendancedate",
                    ),
                ),
            ],
        ),
    ]
