# Generated by Django 4.2.4 on 2023-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_logindata_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logindata",
            name="teacher_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
