# Generated by Django 4.2.4 on 2023-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_alter_logindata_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindata",
            name="batch_id",
            field=models.CharField(default="None", max_length=30),
        ),
    ]
